### PR TITLE
add allowErrors prop

### LINKED ISSUE #161: CodeInline has no way to suppress type errors

### PR DESCRIPTION
**Pull request by hipstersmoothie**
Does it make sense to default this to true?

closes #161

### CODE REVIEW

**Comment by noxify** [comment]
> Does it make sense to default this to true?

Yes and no :) since it doesn't exists currently, it could break some builds if we set it to `true` by default.

**Comment by souporserious** [comment]
Yeah, I think defaulting to `true` makes sense to align with `CodeBlock`. There will be a breaking change soon with moving over to the new collections utility. I'll hold out on this PR until then. Alternatively, we could ship with it set to `false` for now to unblock.

**Comment by hipstersmoothie** [comment]
@souporserious I'm fine with false (which is what it currently is)

**Comment by souporserious** [comment]
My bad, didn't realize this isn't a breaking change, will be out in the next release. I think keeping false by default is good since in an upcoming release this will be type-checked so disabling yourself for now seems best.

**Pull request merged**
